import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";
import { GoogleGenerativeAI } from "@google/generative-ai";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // API Routes
  app.post("/api/designer/generate-config", (req, res) => {
    const { nodes, edges } = req.body;
    
    // Server-side HOCON generation logic
    let hocon = `// Neuro SAN Config Generated by Visual Designer\n// Ref: AAOSA Protocol\n\n`;
    
    hocon += "agents {\n";
    nodes.forEach((node: any) => {
      const neighbors = edges.filter((e: any) => e.source === node.id).map((e: any) => e.target);
      hocon += `  ${node.id.replace(/-/g, '_')} {\n`;
      hocon += `    label = "${node.data.label}"\n`;
      hocon += `    type = "${node.data.type}"\n`;
      hocon += `    prompt = """\n${node.data.prompt}\n"""\n`;
      hocon += `    outputs = [${neighbors.map((n: string) => `"${n.replace(/-/g, '_')}"`).join(', ')}]\n`;
      hocon += `    memory = { type = "vector", ttl = 3600 }\n`;
      hocon += `  }\n`;
    });
    hocon += "}\n\n";

    hocon += "workflows {\n";
    hocon += "  orchestration_dag {\n";
    hocon += `    nodes = [${nodes.map((n: any) => `"${n.id.replace(/-/g, '_')}"`).join(', ')}]\n`;
    hocon += "    strategy = \"delegation\"\n";
    hocon += "  }\n";
    hocon += "}\n";

    res.json({ hocon });
  });

  app.post("/api/designer/run-network", async (req, res) => {
    const { nodes, edges } = req.body;
    
    // Detailed Execution Trace
    const trace: any[] = [
      { step: "INIT", message: "Neuro SAN Runtime initializing...", status: "info", nodeId: null },
      { step: "AUTH", message: "Verifying AAOSA credentials...", status: "info", nodeId: null },
      { step: "LOAD", message: "Loading node configurations into memory...", status: "info", nodeId: null },
    ];

    // Mock complex execution flow
    nodes.forEach((node: any) => {
      trace.push({ step: "EXEC", message: `Executing agent: ${node.data.label} [${node.data.type}]`, status: "running", nodeId: node.id });
      trace.push({ step: "TOOL", message: `Binding tools for ${node.data.label}...`, status: "info" });
    });

    trace.push({ step: "FINISH", message: "Network execution successful.", status: "success" });

    res.json({ trace });
  });

  app.post("/api/designer/validate-config", (req, res) => {
    const { nodes, edges } = req.body;
    const errors = [];
    
    if (nodes.length === 0) errors.push("DAG must contain at least one agent.");
    const hasRouter = nodes.some((n: any) => n.data.type === 'router');
    if (!hasRouter) errors.push("Neuro SAN requires at least one Router for AAOSA compliance.");

    res.json({ valid: errors.length === 0, errors });
  });

  app.post("/api/designer/load-config", (req, res) => {
    const { hocon } = req.body;
    // In a real app, we'd use hocon-parser here. 
    // Since we're in a demo/prototype environment, we'll simulate the successful parsing 
    // of a HOCON string into a DAG.
    
    const nodes = [
      { id: 'imported-router', type: 'agent', position: { x: 100, y: 100 }, data: { label: 'Imported Orchestrator', type: 'router', prompt: 'Imported from HOCON' } },
      { id: 'imported-worker', type: 'agent', position: { x: 300, y: 100 }, data: { label: 'Imported Worker', type: 'worker', prompt: 'Imported from HOCON' } }
    ];
    const edges = [
      { id: 'e-imp-1', source: 'imported-router', target: 'imported-worker' }
    ];

    res.json({ nodes, edges });
  });

  app.post("/api/designer/ai-suggest", async (req, res) => {
    const { nodes } = req.body;
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey || apiKey === "MY_GEMINI_API_KEY") {
      return res.json({ suggestions: [] });
    }

    try {
      const genAI = new GoogleGenerativeAI(apiKey);
      const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });
      
      const promptText = `
        Neuro SAN Agent Network Architect.
        Given these agents:
        ${nodes.map((n: any) => `- ${n.id} (${n.data.type}): ${n.data.label} - ${n.data.prompt}`).join('\n')}
        
        Suggest logical connections (DAG edges) between them.
        Return ONLY a JSON array of objects: [{"source": "id1", "target": "id2"}].
        No other text.
      `;

      const result = await model.generateContent(promptText);
      const text = result.response.text();
      const cleanJson = text.replace(/```json|```/g, '').trim();
      const suggestions = JSON.parse(cleanJson);
      res.json({ suggestions });
    } catch (error) {
      console.error("AI Error:", error);
      res.json({ suggestions: [] });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
