import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";
import { GoogleGenerativeAI } from "@google/generative-ai";
import "dotenv/config";
import parseHocon from "hocon-parser";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // API Routes
  app.post("/api/designer/generate-config", (req, res) => {
    const { nodes, edges } = req.body;
    
    // Server-side HOCON generation logic
    let hocon = `// Neuro SAN Config Generated by Visual Designer\n// Ref: AAOSA Protocol\n\n`;
    
    hocon += "agents {\n";
    nodes.forEach((node: any) => {
      const neighbors = edges.filter((e: any) => e.source === node.id).map((e: any) => e.target);
      hocon += `  ${node.id.replace(/-/g, '_')} {\n`;
      hocon += `    label = "${node.data.label}"\n`;
      hocon += `    type = "${node.data.type}"\n`;
      hocon += `    prompt = """\n${node.data.prompt}\n"""\n`;
      hocon += `    outputs = [${neighbors.map((n: string) => `"${n.replace(/-/g, '_')}"`).join(', ')}]\n`;
      hocon += `    memory = { type = "vector", ttl = 3600 }\n`;
      hocon += `  }\n`;
    });
    hocon += "}\n\n";

    hocon += "workflows {\n";
    hocon += "  orchestration_dag {\n";
    hocon += `    nodes = [${nodes.map((n: any) => `"${n.id.replace(/-/g, '_')}"`).join(', ')}]\n`;
    hocon += "    strategy = \"delegation\"\n";
    hocon += "  }\n";
    hocon += "}\n";

    res.json({ hocon });
  });

  app.post("/api/designer/run-network", async (req, res) => {
    const { nodes, edges } = req.body;
    
    // Detailed Execution Trace
    const trace: any[] = [
      { step: "INIT", message: "Neuro SAN Runtime initializing...", status: "info", nodeId: null },
      { step: "AUTH", message: "Verifying AAOSA credentials...", status: "info", nodeId: null },
      { step: "LOAD", message: "Loading node configurations into memory...", status: "info", nodeId: null },
    ];

    // Mock complex execution flow
    nodes.forEach((node: any) => {
      trace.push({ step: "EXEC", message: `Executing agent: ${node.data.label} [${node.data.type}]`, status: "running", nodeId: node.id });
      trace.push({ step: "TOOL", message: `Binding tools for ${node.data.label}...`, status: "info" });
    });

    trace.push({ step: "FINISH", message: "Network execution successful.", status: "success" });

    res.json({ trace });
  });

  app.post("/api/designer/validate-config", (req, res) => {
    const { nodes, edges } = req.body;
    const errors = [];
    
    if (nodes.length === 0) errors.push("DAG must contain at least one agent.");
    const hasRouter = nodes.some((n: any) => n.data.type === 'router');
    if (!hasRouter) errors.push("Neuro SAN requires at least one Router for AAOSA compliance.");

    res.json({ valid: errors.length === 0, errors });
  });

  app.post("/api/designer/load-config", (req, res) => {
    const { hocon } = req.body;
    try {
      const config = parseHocon(hocon);
      const agents = config.agents || {};
      const nodes: any[] = [];
      const edges: any[] = [];
      
      const agentIds = Object.keys(agents);
      
      agentIds.forEach((id, index) => {
        const agent = agents[id];
        const nodeId = id.replace(/_/g, '-');
        
        nodes.push({
          id: nodeId,
          type: 'agent',
          position: { x: 100 + (index % 3) * 250, y: 100 + Math.floor(index / 3) * 200 },
          data: {
            label: agent.label || id,
            type: agent.type || 'worker',
            prompt: agent.prompt || '',
            status: 'idle',
            errors: []
          }
        });

        if (agent.outputs && Array.isArray(agent.outputs)) {
          agent.outputs.forEach((target: string) => {
            const targetId = target.replace(/_/g, '-');
            edges.push({
              id: `e-${nodeId}-${targetId}`,
              source: nodeId,
              target: targetId,
              animated: true
            });
          });
        }
      });

      res.json({ nodes, edges });
    } catch (err: any) {
      console.error("HOCON Parse Error:", err);
      res.status(400).json({ error: "Failed to parse HOCON: " + err.message });
    }
  });

  app.post("/api/designer/ai-suggest", async (req, res) => {
    const { nodes } = req.body;
    const rawApiKey = process.env.GEMINI_API_KEY;
    const apiKey = rawApiKey?.trim();

    if (!apiKey || apiKey === "YOUR_GEMINI_API_KEY_HERE" || apiKey.length < 10 || apiKey.startsWith("AIzaSyDKxi")) {
      console.warn("AI Architect: Invalid/Missing API Key detected in environment.");
      return res.status(400).json({ 
        error: "GEMINI_API_KEY is missing or invalid. Please provide your actual Gemini API Key in the AI Studio Secrets menu.",
        suggestions: [] 
      });
    }

    try {
      const genAI = new GoogleGenerativeAI(apiKey);
      const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" }); // Use 1.5 flash for speed/reliability
      
      const promptText = `
        As an Agent Network Architect for the Neuro SAN platform, your task is to design logical connections (DAG edges) between autonomous agents.
        
        Neuro SAN Protocol Rules:
        1. Router nodes (Orchestrators) typically connect to Worker nodes.
        2. Workers can connect to other Workers for sequential processing.
        3. DAGs should generally flow from source to sink.

        Available Agents:
        ${nodes.map((n: any) => `- ID: "${n.id}", Type: "${n.data.type}", Name: "${n.data.label}", Role: "${n.data.prompt}"`).join('\n')}
        
        Output only a JSON array of missing logical edges. If a connection already logically exists or nodes are disconnected, suggest the flow.
        Return ONLY valid JSON in format: [{"source": "id1", "target": "id2"}].
        Do not include existing connections.
        Do not include markdown or explanations.
      `;

      const result = await model.generateContent(promptText);
      const text = result.response.text();
      
      // Robust JSON extraction
      const jsonMatch = text.match(/\[[\s\S]*\]/);
      if (!jsonMatch) {
        return res.json({ suggestions: [] });
      }
      
      const suggestions = JSON.parse(jsonMatch[0]);
      res.json({ suggestions });
    } catch (error: any) {
      console.error("AI Architect Error:", error);
      
      // Specifically handle invalid API key errors
      const isInvalidKey = error.message?.includes("API key not valid") || 
                           error.status === 400 ||
                           error.errorDetails?.some((d: any) => d.reason === 'API_KEY_INVALID');

      if (isInvalidKey) {
        return res.status(401).json({ 
          error: "Invalid Gemini API Key. Please ensure your GEMINI_API_KEY is correct in the Secrets menu.",
          suggestions: [] 
        });
      }

      res.status(500).json({ error: "Internal AI processing error", suggestions: [] });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
